language: python
python:
  - "2.7"

before_install:
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


install:
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform


script: 
  - nosetests --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_i8c_3e9b96a6cb_1
  - python -m properform Push 47.88.50.110:15554 asdf_i8c_3e9b96a6cb_1 ./profile_i8c_3e9b96a6cb_1

 #2017-08-11 12:10:06 modified at 0 #2017-08-11 12:10:11 modified at 1