language: python
python:
  - "2.7"

before_install:
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


install:
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform


script: 
  - nosetests --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_i8c_a7d60fd9af_4
  - python -m properform Push 47.88.50.110:15554 asdf_i8c_a7d60fd9af_4 ./profile_i8c_a7d60fd9af_4

 #2017-08-11 12:08:39 modified at 0 #2017-08-11 12:08:45 modified at 1 #2017-08-11 12:08:51 modified at 2 #2017-08-11 12:08:56 modified at 3 #2017-08-11 12:09:02 modified at 4